version: 2
updates:
- package-ecosystem: pip
  directory: "/"
  schedule:
    interval: weekly
    day: monday
    time: "03:22"
  target-branch: main
  labels:
    - CI/CD
    - dependencies
- package-ecosystem: github-actions
  directory: "/"
  schedule:
    interval: daily
    time: "03:41"
  target-branch: main
  labels:
    - CI/CD
