name: CD - Deploy Entities on onto-ns.com

on:
  push:
    branches: [main]
  pull_request:

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    if: github.repository == 'M-ERA-NET-MEDIATE/DataDocumentation'

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup Python 3.10
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -U setuptools wheel
        pip install -r requirements_upload.txt

    - name: Validate all Entities
      run: |
        entities-service validate --format=json -d entities/microstructure
        entities-service validate --format=json -d entities/performance
        entities-service validate --format=json -d entities/properties

    - name: Deploy to onto-ns.com
      if: github.event_name == 'push' && github.ref == 'refs/heads/main'
      run: |
        entities-service
