name: CD - Upload Entities

on:
  push:
    branches: [main]
  pull_request:

jobs:
  update-public-entities:
    name: Update public entities
    runs-on: ubuntu-latest
    if: github.repository_owner == 'M-ERA-NET-MEDIATE'

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -U setuptools wheel
          pip install -r requirements_upload.txt

      - name: Check 'entities-service' CLI version
        run: entities-service --version

      - name: Gather Entities
        run: |
          git diff --name-only ${{ github.event.before }} | grep -E '^entities/.*\.json$' > entities.txt ||:

          if [ -s entities.txt ]; then
            echo "RELEVANT_ENTITIES=true" >> $GITHUB_ENV

            echo "Relevant Entities:"
            cat entities.txt
          else
            echo "RELEVANT_ENTITIES=false" >> $GITHUB_ENV

            echo "No entities to validate (and upload)."
            exit 0
          fi

      - name: Validate Entities
        if: env.RELEVANT_ENTITIES == 'true'
        run: cat entities.txt | entities-service validate --strict --format=json -

      - name: Upload Entities
        if: env.RELEVANT_ENTITIES == 'true' && github.event_name == 'push' && github.ref == 'refs/heads/main'
        run: cat entities.txt | entities-service upload --auto-confirm --strict --format=json -
        env:
          ENTITIES_SERVICE_ACCESS_TOKEN: ${{ secrets.ENTITIES_SERVICE_ACCESS_TOKEN }}
