name: CD - Upload Entities

on:
  push:
    branches: [main]
  pull_request:

jobs:
  update-public-entities:
    name: Update public entities
    runs-on: ubuntu-latest
    if: github.repository_owner == 'M-ERA-NET-MEDIATE'

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -U setuptools wheel
          pip install -r requirements_upload.txt

      - name: Check 'entities-service' CLI version
        run: entities-service --version

      - name: Gather Entities
        run: |
          if [ "${{ github.event_name }}" == "push" ]; then
            SHA_BEFORE="${{ github.event.before }}"
          else
            SHA_BEFORE="${{ github.event.pull_request.base.sha }}"
          fi

          git diff --name-only ${SHA_BEFORE} | grep -E '^entities/.*\.json$' > entities.txt

          echo "Relevant Entities:"
          cat entities.txt

      - name: Validate Entities
        run: cat entities.txt | entities-service validate --format=json -

      - name: Upload Entities
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        run: cat entities.txt | entities-service upload --auto-confirm --format=json -
        env:
          ENTITIES_SERVICE_ACCESS_TOKEN: ${{ secrets.ENTITIES_SERVICE_ACCESS_TOKEN }}
