name: CI - Activate auto-merging for automated PRs

on:
  pull_request_target:
    types:
      - opened
    branches:
      - main

permissions:
  pull-requests: write
  contents: write

jobs:
  automerge-dependabot-prs:
    name: Auto-merge Dependabot PRs
    runs-on: ubuntu-latest
    if: github.repository_owner == 'M-ERA-NET-MEDIATE' && github.actor == 'dependabot[bot]' && github.event.pull_request.user.login == 'dependabot[bot]'

    steps:
      - name: Enable auto-merge for Dependabot PRs
        run: gh pr merge --auto --squash "${{ github.event.pull_request.html_url }}"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
